name: Build and Push Perl Images

on: [push, pull_request]

jobs:
  build-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        variant: [ 'main']
        perl-version: [ '5.014.004' ]
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Clone docker-library/official-images
        run: git clone --depth 1 --single-branch https://github.com/docker-library/official-images.git
      - name: Log in to docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build perl ${{ matrix.perl-version }} image
        run: |
          docker version
          docker build --no-cache -t ${{ secrets.DOCKER_HUB_USERNAME }}/test-repo:perl-${{ matrix.perl-version }} ${{ matrix.perl-version }}-${{ matrix.variant }}-buster
      - name: Inspect image creation and tag time
        run: |
          docker image inspect --format \'{{.Created}}\' ${{ secrets.DOCKER_HUB_USERNAME }}/test-repo:perl-${{ matrix.perl-version }}
          docker image inspect --format \'{{.Metadata.LastTagTime}}\' ${{ secrets.DOCKER_HUB_USERNAME }}/test-repo:perl-${{ matrix.perl-version }}
      - name: Run tests
        run: |
          ./official-images/test/run.sh ${{ secrets.DOCKER_HUB_USERNAME }}/test-repo:perl-${{ matrix.perl-version }}
      - name: Push image
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/test-repo:perl-${{ matrix.perl-version }}
